/*
* generated by Xtext
*/
package jp.ac.titech.cs.se.fwit.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FwitRequirementsModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
