/*
* generated by Xtext
*/
package jp.ac.titech.cs.se.fwit.dsl.ui.contentassist;

import jp.ac.titech.cs.se.fwit.dsl.ui.contentassist.AbstractFwitRequirementsModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FwitRequirementsModelProposalProvider extends AbstractFwitRequirementsModelProposalProvider {

}
