/*
 * generated by Xtext
 */
package jp.ac.titech.cs.se.fwit.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FwitRequirementsModelUiModule extends jp.ac.titech.cs.se.fwit.dsl.ui.AbstractFwitRequirementsModelUiModule {
	public FwitRequirementsModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
