/*
 * generated by Xtext
 */
package jp.ac.titech.cs.se.fwit.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FwitRequirementsModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return jp.ac.titech.cs.se.fwit.dsl.ui.internal.FwitRequirementsModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return jp.ac.titech.cs.se.fwit.dsl.ui.internal.FwitRequirementsModelActivator.getInstance().getInjector("jp.ac.titech.cs.se.fwit.dsl.FwitRequirementsModel");
	}
	
}
