/*
* generated by Xtext
*/
package jp.ac.titech.cs.se.fwit.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jp.ac.titech.cs.se.fwit.dsl.services.FwitRequirementsModelGrammarAccess;

public class FwitRequirementsModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FwitRequirementsModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected jp.ac.titech.cs.se.fwit.dsl.parser.antlr.internal.InternalFwitRequirementsModelParser createParser(XtextTokenStream stream) {
		return new jp.ac.titech.cs.se.fwit.dsl.parser.antlr.internal.InternalFwitRequirementsModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FwitRequirementModel";
	}
	
	public FwitRequirementsModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FwitRequirementsModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
