/*
 * generated by Xtext
 */
package jp.ac.titech.cs.se.fwit.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FwitRequirementsModelRuntimeModule extends jp.ac.titech.cs.se.fwit.dsl.AbstractFwitRequirementsModelRuntimeModule {

}
